MODEL_PATHS = {
    "olmo2-0.5T": "/home/share/models/olmo2-7b-0.5T",
    "olmo2-1T": "/home/share/models/olmo2-7b-1T",
    "olmo2-1.5T": "/home/share/models/olmo2-7b-1.5T",
    "olmo2-2T": "/home/share/models/olmo2-7b-2T",
    "olmo2-2.5T": "/home/share/models/olmo2-7b-2.5T",
    "olmo2-3T": "/home/share/models/olmo2-7b-3T",
    "olmo2-3.5T": "/home/share/models/olmo2-7b-3.5T",
    "olmo2": "/home/share/models/olmo2-7b",
    "deepseek-api": "/home/share/models/DeepSeek-R1-Distill-Llama-8B",
    "llama3":"/home/share/models/Meta-Llama-3-8B-Instruct",
    "llama3.1-8B":"/home/share/models/Meta-Llama-3.1-8B-Instruct",
    "llama3.1-70B":"/home/share/models/Meta-Llama-3.1-70B-Instruct",
    "llama3.1-base-8B":"/home/share/models/Meta-Llama-3.1-8B",
    "llama3.1-base-70B":"/home/share/models/Meta-Llama-3.1-70B",
    "deepseek-llama3.1":"/home/share/models/DeepSeek-R1-Distill-Llama-8B",
    "llama2": "/home/share/models/Llama-2-7b-chat-hf",
    "llama2-13b":"/home/share/models/Llama-2-13b-chat",
    "mistral":"/home/share/models/Mistral-7B-Instruct",
    "wizardmath":"/home/share/models/WizardMath-7B",
    "wizardmath1.1": "/home/share/models/WizardMath-7B-v1.1",
    "mathcoder":"/home/share/models/MathCoder2-8B",
    "vicuna": "/home/share/models/vicuna-7b-v1.3",
    "vicuna-13b": "/home/share/models/vicuna-13B/",
    "gemma2": "/home/share/models/gemma-2-9b-it",
    "gemma2-base": "/home/share/models/gemma-2-9b/",
    "gpt-4o": None,
    "gemma2-27b": "/home/share/models/gemma-2-27b-it/",
    "qwen2.5-7B": "/home/share/models/Qwen2.5-7B-Instruct",
    "deepseek-qwen2.5":"/home/share/models/DeepSeek-R1-Distill-Qwen-7B",
    "qwen1.5": "/home/share/models/Qwen1.5-7B-Chat",
    "codellama2":"/home/share/models/CodeLlama-7b",
    "qwen2.5coder":"/home/share/models/Qwen2.5-Coder-7B-Instruct",
    "qwen2.5math":"/home/share/models/Qwen2.5-Math-7B-Instruct",
    "zephyr":"/home/share/models/zephyr-7b-beta",
    "mistral":"/home/share/models/Mistral-7B-Instruct-v0.2",
    "phi-3":"/home/share/models/Phi-3-small-8k-instruct",
    "granite":"/home/share/models/granite-3.1-8b-instruct",
    "aya":"/home/share/models/aya-expanse-8b",
    "tulu3":"/home/share/models/Llama-3.1-Tulu-3-8B",
    "gemma2-simpo": "/home/share/models/gemma-2-9b-it-SimPO",
    "ministral":"/home/share/models/Ministral-8B-Instruct-2410",
    "qwen2.5-base-7B": "/home/share/models/Qwen2.5-7B",
    "qwen2.5-base-32B": "/home/share/models/Qwen2.5-32B",
    "qwen2.5-32B": "/home/share/models/Qwen2.5-32B-Instruct"

}